### PR TITLE
Push issuedAt time 10 seconds into the past for clock skew

### PR DESCRIPTION
**Pull request by ozten**
- Temporary fix for mozilla/jwcrypto/issues/58

### CODE REVIEW

**Comment by ozten** [comment]
@lloyd or @warner - I need a code review.

This preempts https://github.com/mozilla/jwcrypto/pull/59

**Comment by ozten** [comment]
Added comment per lloyd. He was r+ via email.

**Comment by lloyd** [comment]
sorry my r+ was so clumsy, executed on a mobile device.

**Comment by ozten** [comment]
I'll take an r+ anyway I can get one.

However... a r- via mobile... would not be cool ;)

**Pull request merged**
