### PR TITLE
Adding var_path to be consistent with browserid/bigtent

### PR DESCRIPTION
**Pull request by ozten**
Make logging more consistent with browserid.

/cc @gene1wood

### CODE REVIEW

**Comment by jrgm** [comment]
r+

**Comment by jrgm** [comment]
... and adding 'var_path' to the certifier production.json, right?

**Comment by ozten** [comment]
There is no such file. This is an ops tweak.

**Comment by jrgm** [comment]
Sorry, that's what I meant. 

(Although, on a side note, and not just about bigtent, I think we should get away from foo/config/production.json being completely overwritten; instead there should just be an override file for tweaks added to CONFIG_FILES chain).

**Comment by ozten** [comment]
+1

**Comment by gene1wood** [comment]
r+, merge away

**Pull request merged**
